### ISSUE TITLE
Support for Taffy 0.5

### ISSUE THREAD

**Issue by mortencombat** [mortencombat/stretchable#86]
Includes support for block layout, overflow/scrollable layouts and reworked measure functions.

**Comment by baseplate-admin** [comment]
Hi, do you have a release plan for this?

**Comment by mortencombat** [comment]
> Hi, do you have a release plan for this?

I don't have a timeline atm I'm afraid, been busy with life and have a busy summer coming up, but early fall would be a good bet.
