### ISSUE TITLE
`measure` kwarg to Node constructor doesn't function

### ISSUE THREAD

**Issue by mfenniak** [mortencombat/stretchable#87]
`Node.__init__` stores the measure function in `_measure`, but doesn't invoke the measure property setter function, and therefore `taffylib.node_set_measure` is never invoked and the function is never used by taffy.

https://github.com/mortencombat/stretchable/blob/4b78715c0730059f101e469c6363e24470763dc9/src/stretchable/node.py#L160

Workaround: don't use the measure kwarg, and instead use the `measure` property to set the measure on the node after constructor.

(This library is great!  Just what I was looking for.  Thank you for creating it.)

**Comment by mortencombat** [comment]
Good catch @mfenniak, thanks! Both of your PRs #89 (fixing #88) and #90 (fixing #87) have been merged and are included in [v1.0.1](https://github.com/mortencombat/stretchable/releases/tag/v1.0.1).

**Comment by mfenniak** [comment]
@mortencombat Thanks for the quick merges and new release. 🙂
